### ISSUE TITLE
Add Entity for Clients

### ISSUE THREAD

**Issue by yurii-polishchuk** [yurii-polishchuk/ipcount-core#19]
- add entity mapping.
 - add simple validators.
 - tostirng, equals, hashcode, getters,setters.

**Comment by yurii-polishchuk** [comment]
map on DTO object from backend

**Comment by anMelnyk** [comment]
@Oksana1788 please proceed with this task after you finish with maven wrapper.

**Comment by yurii-polishchuk** [comment]
Entity added.
