### ISSUE TITLE
Create project skeleton (back-end part)

### ISSUE THREAD

**Issue by yurii-polishchuk** [yurii-polishchuk/ipcount-core#4]
1. Create basic folder structure. Please follow guides: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
2. Add Maven 
3. Ad basic Main class with main method.

**Comment by Oksana1788** [comment]
@yurii-polishchuk ang @anMelnyk Can I call folder in project skeleton "com.ipcount.core"?

**Comment by yurii-polishchuk** [comment]
@Oksana1788 sure, we don't have specific domain name, so feel free to name it as com.ipcount.core

**Comment by yurii-polishchuk** [comment]
Good for now, but we will need to extend skeleton structure later. (tests, infrastructure, etc)
